### PR TITLE
Added support for require()

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Adds seamless support for standard Lua modules with `require(filename)` syntax.

`require()` statements are resolved when Atom saves and pushes to TTS. When this happens a bundle is generated with marker comments, much like `#include`. Unbundling occurs when we pull files from TTS, again, similar to how `#include` works.

Two new configuration options have been added to the Atom extension:

* "require() other files" toggle (default enabled, but can be disabled like `#include`)
* "Bundle file patterns", which is how Lua resolves require file paths (https://www.lua.org/pil/8.1.html). Sensible default chosen.

Files are resolved relative to the existing `includeOtherFilesPath` option, and text has been updated to reflect this.

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
Actually, don't bother reviewing this just yet. I'm going to make it _much_ simpler.

**Comment by onelivesleft** [comment]
You need to explain what it's doing that wouldn't be accomplished by just changing the `#include` string to `require`, bearing in mind that `#include` is deliberately called that and not `require`, because it doesn't have the same functionality: `require` would make the user think they could `require os` or `require debug`, or more importantly, require some library compiled from C.
There's no confusion about capability when you have a new preprocessor instruction, but plenty of gotchas when you override a standard lua keyword with semantics different from the norm.

**Comment by Benjamin-Dobell** [comment]
Sorry, my apologies. My background is obviously a bit different!

# Bundlers

In the "wonderful world of web world development" (_sarcasm very much intended_) bundlers are the norm, so don't warrant further explanation. However, if you're fortunate enough to have steered clear of that world; well, you're very luck! :wink:

Common web bundlers:
* [webpack](https://webpack.js.org/)
* [rollup](https://rollupjs.org/)

Module bundlers are quite different than just concatenating code (`#include`) and serve a different purpose.`#include` (i.e. file concatenation) is suitable for compiled languages, however dynamic/scripting languages (Node.JS, Lua, Python, Ruby etc.) all allow you to load code _at runtime. This Atom extension itself running in Node.JS and doing just that.

# Issues with `#include`

There are several _major_ flaws with simply concatenating files in dynamic/scripting languages; these issues are not present in compiled languages.

1. All code runs in the same context. If I define:

```lua
local name
```

There's a very good chance that's going to collide with another "local" variable.

This a _major_ issue for code reuse. You can't share code with other users and expect it to work.

There was a change in this extension at one point to wrap code in `do ... end` blocks. That at least eliminates this issue. However, that caused another problem, what if you _want_ to share variables (typically "classes") between files?

Your only option is to write to a global variable, however, we're back where we started; there's far too much potential for name collisions.

What we really need is a safe scope to define our own variables, then _explicitly_ share something from our module.

This is actually how this very Atom extension works, we however our own scope, then export just the extension itself using `module.exports`. Then Atom loads this extension, there's no possibility of us accidentally overwriting variables of other extensions, even though we're running in the very same Node.js context.

2. Functions?

The above issue can be "solved" if `#include` simply wrapped file in `function() ... end` rather than `do ... end`, which is precisely. _Actually_, that's precisely what all code bundlers (including the one used here) do. However, it's more nuanced than that...

Let's assume `#include` was changed to do just that, wrap code in functions. We now have a local scope, and we can return a variable. Let's then assume this plugin allowed the following syntax:

**a.ttslua**
```lua
local TableUtils = #include TableUtils.ttslua

#include b.ttslua
```

Looking good so far...

```lua
local TableUtils = #include TableUtils.ttslua -- Uh, oh!
```

This extension only allows you to include a file once, and for good reason. Unlike compiled languages, Lua allows files to have side effects i.e. code is run immediately when it's read.

3. Dynamic languages allow you to dynamically require code e.g.

```lua
if some_condition then
   require("./module_a")
else
   require("./module_b")
end

if feeling_great then
   require("module_a") -- Uh oh!
end
```

If you substitute out those `require()` calls for "equivalent" `#include` you've got a big problem. As above, this plugin only allows you to include the code once, that second "include" would be completely removed from the file `module_a` is never loaded. This is exacerbated by the fact that Lua, unlike compiled languages, _allows_ side effects in the root. So if for example `module_a` was supposed create a TTS event listener (global function), it simply won't happen.

# Conclusion

The reasons above are _why_ Lua doesn't have a `#include` statement, but instead uses `require()`. Where as compiled languages like C use `#include` but don't allow dynamically loaded code (because they can't interpret it at runtime, not a VM).

4. **(Bonus point)** Using _real_ Lua modules

By implementing `require()` we're a step closer to using real Lua modules (i.e. those available from LuaRocks), rather than needing to custom implement everything, We can take advantage of a huge existing body of work.

Well, additionally, with this change we can all start reliably sharing our code with others. At present there's no way to reliably share code with other TTS users i.e. including other user's code may break your own code (for the reasons above).

# Addressing your comments

> #include is deliberately called that and not require, because it doesn't have the same functionality: require would make the user think they could require os or require debug, or more importantly, require some library compiled from C.
There's no confusion about capability when you have a new preprocessor instruction, but plenty of gotchas when you override a standard lua keyword with semantics different from the norm.

Firstly, I should probably add there's actually nothing already stopping users from writing:

```lua
require("os")
```

This of course raises an error in TTS, and it's not obvious why, because this is standard Lua.

_However_, this PR actually addresses that. You'll get an error, up front, stating that "os" _cannot_ be required - well, unless the user provides a file called `os.ttslua` for some reason.

What is really confusing to users and happens fairly regularly (based on observations on Discord) is newbie users think they can download some Lua code from the Internet, and it'll work. The process goes something like:

1. Try copy and paste into TTS' script editor

_Dang!_ It's multiple files.

2. Try concatenate them in the in-built script editor.

No dice. That's not how the code is written.

3. The user identifies they need support for external files

They checkout the Wiki and find Atom and this plugin (or are referred to it on Discord).

Of course, they download Atom, go to the effort of setting it up, drop the code in correct location. _Then_ they try `require()` it, because that's what the docs for the library say to do.

_Boom!_ Still doesn't work.

4. Learn about `#include`

Let's assume the user hasn't given up already. They may go further and realise TTS supports `#include`.

So their next step will be to naively  `#include` every file into one file in TTS.

Again, that fails, internally, those files `require()` each other

5. Replace `require()` with `#include`

Next, they search for all instances of `require()` and replace them with `#include`. Assuming they work out that the syntax is different, and they get real lucky and the library doesn't do anything like:

```lua
require('this_module/b')("param 1", "param 2")
```

It _still_ doesn't work. For all the reasons listed above i.e.  code has side effects, the order is important and you can't `#include` the same file multiple times.

**What about this PR?**

A user makes it to step 3 and...

_it works!_

Lua libraries tend to be small and self-contained. If the project they were after was something complicated and uses a dependency manager like LuaRocks, they'd be in trouble.

_However_, assuming the user knows how to set it up, this PR will even work with LuaRocks. It'll recursively bundle up all dependencies, no worries.

**Comment by onelivesleft** [comment]
Are all LuaRocks packages pure lua?

**Comment by Benjamin-Dobell** [comment]
No, there are different types of rocks, some are pure Lua, some aren't etc:

https://github.com/luarocks/luarocks/wiki/Types-of-rocks

Granted, although I've mentioned LuaRocks above. This PR doesn't _technically_ have anything to do with LuaRocks. I'm not at all expecting your average TTS user to understand dependency management and have access to a working Lua CLI.

Technically this extension could integrate with LuaRocks if we _really_ wanted to support that. However, I think extracting a zip files with reliably reusable code is probably the sweet spot for your average TTS user.

# What I'm hoping for...

1. Download a TTS specific library as a zip file e.g. [my "ge_tts" library](https://gitlab.com/BenjaminDobell/ge_tts/-/archive/master/ge_tts-master.zip)

2. Extract it to your TTS Lua directory (same one you include files from).

3. Write something like:

```lua
local Coroutine = require('ge_tts/Coroutine')

Coroutine.start(function()
    for i = 1, 10 do
        print('Waiting 1 second ' .. i .. '/10...')
        Coroutine.yieldSeconds(1)
    end
     for i = 1, 10 do
        print('Waiting 1 frame ' .. i .. '/10...')
        Coroutine.yieldFrames(1)
    end
    for i = 1, 10 do
        print('Waiting 100 frames ' .. i .. '/10...')
        Coroutine.yieldFrames(100)
    end
end)
```
_Woohoo!_ A new coroutine syntax that's way easier to follow.

Or some reusable table utilities (which realistically we all need):

```lua
local TableUtils = require('TableUtils') -- The user's TableUtils

TableUtils.merge({a=1, c = 3}, {b = 2})
```
etc.

Right now, we can't reliably share code with each other. For instance, I've called my table utilities `TableUtils`, it's highly likely someone else has done the same.

If I wasn't using modules, they would collide. However, instead it's as simple as

```lua
local TableUtils = require('TableUtils') -- The user's TableUtils
local GeTtsTableUtils = require('TableUtils') -- ge_tts TableUtils, with a different local name

GeTtsTableUtils.merge({a=1, c = 3}, {b = 2})

TableUtils.chopsuey({a=1, b=2, c=3}) -- Phew! My `TableUtils` does not provide a chopsuey method
```

**Comment by onelivesleft** [comment]
It would also have to search the paths lua would look at for require.  

I asked about lua rocks because inevitably people will be asking "Why does require work for this package but not that package?"

**Comment by Benjamin-Dobell** [comment]
Lua is a bit different than say Python etc. with its system-wide `site-packages` etc. There is no default location on your PC for libraries. 

The default search path is `?;?.lua`[1](https://www.lua.org/pil/8.1.html), which will effectively require relative to your current working directory.

In the case of this Atom extension, for all intensive purposes the current working directory is the include directory defined in settings, by default, we do search there. (Default: `?.ttslua;?.lua`). So we're doing what a user would expect.

> I asked about lua rocks because inevitably people will be asking "Why does require work for this package but not that package?

Lua doesn't come with a package manager, so I don't think there's that expectation. It's not like Node.js or Python where you expect to be able to do something like:

```bash
npm install -g some_package
```

There are no system wide packages. The kind of user that:

* knows how to write scripts
* knows about this extension
* knows about LuaRocks
* knows how to install LuaRocks; not exactly [straight-forward](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows)

isn't likely to complain.

This PR isn't about LuaRocks, _I_ don't even have LuaRocks setup on my system. The references to it were purely to demonstrate how robust this solution is; however, what necessitates this functionality is the much simpler desire to be able to reliably share code (well, and not shoot myself in the foot even with my own code!)

**Comment by onelivesleft** [comment]
Try not to get hung up on luarocks, my point is this will work with pure lua packages but not anything compiled.

**Comment by Benjamin-Dobell** [comment]
> Try not to get hung up on luarocks, my point is this will work with pure lua packages but not anything compiled.

Absolutely.

There are other limitations too i.e the same limitations of other module bundler. an all other bundlers e.g.

```lua
local Thing = require(someVariable) -- Hmm?
```

We show a warning in Atom in this circumstance, but otherwise continue on.

This may be perfectly fine e.g.

```lua
local Hat = require('hat')
local Scarf = require('scarf')

local someVariable = math.random(2) == 1 and 'hat' or 'scarf'

local Thing = require(someVariable)
```

Despite the warning, that'll resolve just fine at runtime. This is because we detected both 'hat' and 'scarf' in other `require()` statements, so they're bundled up just fine.

However, it'd be wise to rewrite it as:

```lua
local Thing = math.random(2) == 1 and require('hat') else require('scarf')
```

Which will dismiss the warning because it's no longer ambiguous as to what should be included in the bundle. In the very first example `someVariable` could be anything at all, at bundle time we can't infer what modules we should put in the bundle.

This isn't unique to Lua, the aforementioned web bundlers have the same limitation, although webpack has some serious smarts regarding stuff like `require('a_directory/' + variable)`, auto-bundles all files matching `a_directory/*.js`.

However, for our purposes a warning (and perhaps an explanatory Wiki entry) ought to suffice.

By the way, regarding the usefulness of bundles to an individual (as opposed to just for sharing code). I've been using Lua bundles in TTS for over a year (a previous crappy incarnation of what we have here).

Even within the one project, I have several Lua "classes" that have the same name (intentionally).

Screen Shot 2020-01-18 at 5 44 02 am

In this case the inheritances hierarchy goes:

* Zone (ge_tts)
* DropZone (ge_tts)
* PlayerDropZone (ge_tts)
* **DropZone (prototype_inertia)**
* BattlefieldZone, BuildingZone, DeadZone, DeckZone, EnergyZone (prototype_inertia)
* ... further sub-classing (in some cases)

The logic being that for my Prototype Inertia game; drop zones (TTS scripting zones with predefined functionality) will _always_ belong to a player and have other game specific logic. So I'll not usually want to refer to ge_tts `DropZone`, yet they don't clash, and if I really want I can still explicitly `require()` both files in the one Lua file like I did above with my `TableUtils` example.

**Comment by Benjamin-Dobell** [comment]
@onelivesleft Sorry, I know it's only the `test` branch, but you'll definitely want to revert that merge; or just hard reset as I seriously doubt anyone has pulled it down yet.

There are some bugs that both myself and Discord user "Omniraptor" have run into in our testing.

However, I've also got a much cleaner implementation I was planning on updating this PR with. however it's not quite done yet.

**Comment by onelivesleft** [comment]
I've merged your PRs into the `test` branch.  

* `require` chokes when it tries to bundle `#include`
* After a save & play without any require, it gets back blank files.

**Comment by onelivesleft** [comment]
OK, please work on the test branch and let me know when you're good with it.

**Comment by Benjamin-Dobell** [comment]
Alright, will do. Won't be until next week at the earliest, as I'm camping this weekend - no computers for me 😉

I don't at all mind if you make a new release without this. I'd rather it be implemented and tested properly than rush the feature through.

**Comment by onelivesleft** [comment]
There's only two very minor bug fixes apart from your stuff, so no rush.
HF in the woods!

**Pull request merged**
